backend:
  name: git-gateway
  site_domain: animated-panda-82f1b2.netlify.app
  branch: main

media_folder: "images/uploads"
public_folder: "images/uploads"

collections:
  - name: "articoli"
    label: "Articoli del Giornalino"
    folder: "_articoli"
    create: true
    slug: "{{slug}}"
    fields:
      - {label: "Titolo dell'Articolo", name: "title", widget: "string"}
      - {label: "Data di Pubblicazione", name: "date", widget: "datetime"}
      - {label: "Categoria", name: "category", widget: "select", options: ["Guida Pratica", "Cultura & Vita", "Viaggi", "Eventi"]}
      - {label: "Nome Autore", name: "author", widget: "string", default: "Redazione ERasMES"}
      - {label: "Foto di Copertina", name: "image", widget: "image"}
      - {label: "Breve Riassunto (per la Home)", name: "excerpt", widget: "text"}
      - {label: "Testo dell'Articolo", name: "body", widget: "markdown"}
